// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFK5sqxxo34Tgbm04D7AXw8y6atxg6gRo',
    appId: '1:919151871318:android:e0ecb8bbdb9517437c82f7',
    messagingSenderId: '919151871318',
    projectId: 'eta-network-test',
    storageBucket: 'eta-network-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-IoktoywZ8JCTpdbEDeaomHKVuZOeoas',
    appId: '1:919151871318:ios:94b8973fb9a3d9077c82f7',
    messagingSenderId: '919151871318',
    projectId: 'eta-network-test',
    storageBucket: 'eta-network-test.firebasestorage.app',
    androidClientId:
        '919151871318-66bhmtrhrt1h9eevpmbhsot7l6eilarg.apps.googleusercontent.com',
    iosClientId:
        '919151871318-72bdhl0mlghv4irsvcte1ddfsp7e271g.apps.googleusercontent.com',
    iosBundleId: 'net.etanetwork.app.test',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfOwxoY6j3-hBCE5nzneUz7tRJEgkbSQs',
    appId: '1:919151871318:web:a372591ad6ab82a07c82f7',
    messagingSenderId: '919151871318',
    projectId: 'eta-network-test',
    authDomain: 'eta-network-test.firebaseapp.com',
    storageBucket: 'eta-network-test.firebasestorage.app',
    measurementId: 'G-LV280C16BT',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfOwxoY6j3-hBCE5nzneUz7tRJEgkbSQs',
    appId: '1:919151871318:web:a372591ad6ab82a07c82f7',
    messagingSenderId: '919151871318',
    projectId: 'eta-network-test',
    authDomain: 'eta-network-test.firebaseapp.com',
    storageBucket: 'eta-network-test.firebasestorage.app',
    measurementId: 'G-LV280C16BT',
  );
}
