// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Uj54UhqO1DBuEPNWkwLAat12Mp13qZc',
    appId: '1:899853959610:android:3e70022c18d0a8dbb31d83',
    messagingSenderId: '899853959610',
    projectId: 'eta-network-31964',
    storageBucket: 'eta-network-31964.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRYhSiYRh9kRkPHV1NKSHcOYDp9WgRcvs',
    appId: '1:899853959610:ios:0abf91e974ce1c92b31d83',
    messagingSenderId: '899853959610',
    projectId: 'eta-network-31964',
    storageBucket: 'eta-network-31964.firebasestorage.app',
    androidClientId: '899853959610-euk59ct1o7u65derouq8muiu8fh7si2m.apps.googleusercontent.com',
    iosClientId: '899853959610-0jfkmj1ao4bgrjj95pqapal9r9qki5l9.apps.googleusercontent.com',
    iosBundleId: 'net.ApexSoft.EtaNetwork',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdVZ48BWKKXG7Xc1e97mKyKcssHIF2fz0',
    appId: '1:899853959610:web:344ca8ceca463376b31d83',
    messagingSenderId: '899853959610',
    projectId: 'eta-network-31964',
    authDomain: 'eta-network-31964.firebaseapp.com',
    storageBucket: 'eta-network-31964.firebasestorage.app',
    measurementId: 'G-6TCV239WMP',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdVZ48BWKKXG7Xc1e97mKyKcssHIF2fz0',
    appId: '1:899853959610:web:99cae1604971329cb31d83',
    messagingSenderId: '899853959610',
    projectId: 'eta-network-31964',
    authDomain: 'eta-network-31964.firebaseapp.com',
    storageBucket: 'eta-network-31964.firebasestorage.app',
    measurementId: 'G-048TGLLK3F',
  );

}